apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  trafficManagement:
    enabled: false
  policy:
    enabled: false
  telemetry:
    enabled: false
  security:
    enabled: false
  configManagement:
    enabled: false
  autoInjection:
    enabled: false
  gateways:
    components:
       ingressGateway:
         enabled: true
         namespace: bookinfo
       egressGateway:
         enabled: false
  values:
    prometheus:
      enabled: false
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: private